In [95]:
library(HMM)
library(mclust)

In [96]:
dim(faithful)
head(faithful)

[1] 272   2

eruptions waiting
1 3.600     79     
2 1.800     54     
3 3.333     74     
4 2.283     62     
5 4.533     85     
6 2.883     55

In [97]:
mygauss <- function(data, mean, Sigma){
    p = nrow(Sigma)
    svd_obj = svd(Sigma)
    D = svd_obj$d
    U = svd_obj$u
    V = svd_obj$v
    Dt = diag(1/sqrt(D))
    A = t(data)
    Sinv = U %*% Dt^2 %*% t(U) 

    #xt = Dt %*% t(U) %*% data
    #mt = Dt %*% t(U) %*% mean
    #a = t(xt-mt) %*% Sinv %*% (xt-mt)
    a = (A - mean) * (Sinv %*% (A - mean))
    a = colSums(a)
    return (exp(-0.5 * a)/((2*pi)^p * (det(Sigma))^0.5))
}

Estep <- function(data, G, para){
    # Your Code
    prob <- para$prob
    mu <- para$mean
    Sigma <- para$Sigma
    loglik <- para$loglik
    n <- nrow(data)
    # need to come up with a way to evalue multivariate gaussian distrbutions,
    # but let's focus on getting the algorithm correct right now.
    # assume we have G means, G Sigmas, G pis
    p = matrix(0, n, G)
    for (k in 1:G){
        p[,k] = prob[k] * mygauss(data, mu[,k], Sigma)
    }
    #p = prob * mygauss(data, mu, Sigma)
    s = rowSums(p)
    p = p / s
  
    # Return the n-by-G probability matrix
    return(p)
  }

Mstep <- function(data, G, para, post.prob){ 
    # Your Code
    # Return the updated parameters
    para$prob = colSums(post.prob) / nrow(post.prob)
    mu = t(data) %*% post.prob
    #mu_sum = colSums(mu)
    mu_sum = colSums(post.prob)
    n = nrow(mu)
    for (k in 1:n){
        mu[k,] = mu[k,] / mu_sum
    }
    para$mean = mu
    Sigma = matrix(0, n, n)
    # This loop is giving the first step Sigma very close agreement with the 
    # R method, but not exact agreement. 
    for (k in 1:G) {
        x = t(data) - mu[,k]
        P = diag(post.prob[,k])
        Sigma = Sigma + x %*% P %*% t(x)   
    }
    
    para$Sigma = Sigma / (colSums(post.prob) * n)
    
    return (para)
  }

loglik <- function(data, G, para){
    # compute loglikelihood
    ll = para$loglik
    
    return (ll)
}

myEM <- function(data, itmax, G, para){
  # itmax: number of of iterations
  # G:     number of components
  # para:  list of (prob, mean, Sigma, loglik)
  d = as.matrix(data)
  for(t in 1:itmax){
    print(t)
    #print(para$Sigma)
    post.prob <- Estep(d, G, para)
    #print(post.prob)
    para <- Mstep(d, G, para, post.prob)
  }
  
  # update para$loglik   
  #para[4] = loglik(data, G, para)
  
  return(para)
}

In [98]:
n <- nrow(faithful)
G <- 2
set.seed(7568)  # replace 234 by the last 4-dig of your University ID
gID <- sample(1:G, n, replace = TRUE)
Z <- matrix(0, n, G)
for(k in 1:G)
  Z[gID == k, k] <- 1 
ini0 <- mstep(modelName="EEE", faithful , Z)$parameters

In [99]:
para0 <- list(prob = ini0$pro, 
              mean = ini0$mean,
              Sigma = ini0$variance$Sigma, 
              loglik = NULL)

In [100]:
myEM(d=faithful, itmax=20, G=G, para=para0)

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20


$prob
[1] 0.6403993 0.3596007

$mean
              [,1]      [,2]
eruptions  4.29694  2.046786
waiting   80.04005 54.614647

$Sigma
          eruptions    waiting
eruptions 0.1030181  0.5866558
waiting   1.0447530 49.0457998

$loglik
NULL

In [101]:
# Test E step
para_test <- list(pro = ini0$pro,
                  mean = ini0$mean,
                  variance = ini0$variance,
                  Vinv = NULL)
estep(data=faithful, modelName="EEE", parameters=para_test)$z

[,1]      [,2]     
1   0.4783272 0.5216728
2   0.4464928 0.5535072
3   0.4819229 0.5180771
4   0.4467317 0.5532683
5   0.5398228 0.4601772
6   0.5561139 0.4438861
7   0.5384024 0.4615976
8   0.4398103 0.5601897
9   0.4818333 0.5181667
10  0.5202056 0.4797944
11  0.4500055 0.5499945
12  0.4801026 0.5198974
13  0.5491799 0.4508201
14  0.4861734 0.5138266
15  0.5703391 0.4296609
16  0.4987083 0.5012917
17  0.3909580 0.6090420
18  0.5745427 0.4254573
19  0.4380198 0.5619802
20  0.5481040 0.4518960
21  0.4657392 0.5342608
22  0.4861734 0.5138266
23  0.4686808 0.5313192
24  0.4856281 0.5143719
25  0.6092446 0.3907554
26  0.4525920 0.5474080
27  0.4578901 0.5421099
28  0.5495196 0.4504804
29  0.5116775 0.4883225
30  0.5675289 0.4324711
⋮   ⋮         ⋮        
243 0.5758901 0.4241099
244 0.5064513 0.4935487
245 0.5451639 0.4548361
246 0.4839914 0.5160086
247 0.4574427 0.5425573
248 0.5413495 0.4586505
249 0.3994478 0.6005522
250 0.5903410 0.4096590
251 0.4893285 0.5106715
252 0.5437962 0.4562038
253 0.5135561 0.4864439
254 0.6120172 0.3879828
255 0.4793102 0.5206898
256 0.4951967 0.5048033
257 0.5638018 0.4361982
258 0.5437962 0.4562038
259 0.4549969 0.5450031
260 0.5516195 0.4483805
261 0.6085910 0.3914090
262 0.5462409 0.4537591
263 0.4263425 0.5736575
264 0.5223739 0.4776261
265 0.5370370 0.4629630
266 0.4560242 0.5439758
267 0.6251979 0.3748021
268 0.5209980 0.4790020
269 0.5356153 0.4643847
270 0.4950954 0.5049046
271 0.4998451 0.5001549
272 0.6024614 0.3975386

In [102]:
d = as.matrix(faithful)
G = 2
post.prob <- Estep(d, G, para0)
post.prob

[,1]      [,2]     
 [1,] 0.4783272 0.5216728
 [2,] 0.4464928 0.5535072
 [3,] 0.4819229 0.5180771
 [4,] 0.4467317 0.5532683
 [5,] 0.5398228 0.4601772
 [6,] 0.5561139 0.4438861
 [7,] 0.5384024 0.4615976
 [8,] 0.4398103 0.5601897
 [9,] 0.4818333 0.5181667
[10,] 0.5202056 0.4797944
[11,] 0.4500055 0.5499945
[12,] 0.4801026 0.5198974
[13,] 0.5491799 0.4508201
[14,] 0.4861734 0.5138266
[15,] 0.5703391 0.4296609
[16,] 0.4987083 0.5012917
[17,] 0.3909580 0.6090420
[18,] 0.5745427 0.4254573
[19,] 0.4380198 0.5619802
[20,] 0.5481040 0.4518960
[21,] 0.4657392 0.5342608
[22,] 0.4861734 0.5138266
[23,] 0.4686808 0.5313192
[24,] 0.4856281 0.5143719
[25,] 0.6092446 0.3907554
[26,] 0.4525920 0.5474080
[27,] 0.4578901 0.5421099
[28,] 0.5495196 0.4504804
[29,] 0.5116775 0.4883225
[30,] 0.5675289 0.4324711
[31,] ⋮         ⋮        
[32,] 0.5758901 0.4241099
[33,] 0.5064513 0.4935487
[34,] 0.5451639 0.4548361
[35,] 0.4839914 0.5160086
[36,] 0.4574427 0.5425573
[37,] 0.5413495 0.4586505
[38,] 0.3994478 0.6005522
[39,] 0.5903410 0.4096590
[40,] 0.4893285 0.5106715
[41,] 0.5437962 0.4562038
[42,] 0.5135561 0.4864439
[43,] 0.6120172 0.3879828
[44,] 0.4793102 0.5206898
[45,] 0.4951967 0.5048033
[46,] 0.5638018 0.4361982
[47,] 0.5437962 0.4562038
[48,] 0.4549969 0.5450031
[49,] 0.5516195 0.4483805
[50,] 0.6085910 0.3914090
[51,] 0.5462409 0.4537591
[52,] 0.4263425 0.5736575
[53,] 0.5223739 0.4776261
[54,] 0.5370370 0.4629630
[55,] 0.4560242 0.5439758
[56,] 0.6251979 0.3748021
[57,] 0.5209980 0.4790020
[58,] 0.5356153 0.4643847
[59,] 0.4950954 0.5049046
[60,] 0.4998451 0.5001549
[61,] 0.6024614 0.3975386

In [103]:
# Test MStep
testm_res <- mstep(data=faithful, modelName="EEE", z = post.prob)$parameters

In [104]:
para <- Mstep(d, G, para0, post.prob)
para

$prob
[1] 0.5184054 0.4815946

$mean
              [,1]      [,2]
eruptions  3.58252  3.385804
waiting   71.48603 70.263065

$Sigma
          eruptions   waiting
eruptions  1.242539  13.37405
waiting   14.396295 190.79367

$loglik
NULL

In [105]:
testm_res$variance$Sigma

eruptions waiting  
eruptions  1.288278  13.86636
waiting   13.866356 183.77041

# Problem 2

In [324]:
myBW = function(x, para, n.iter = 100){
  # Input:
  # x: T-by-1 observation sequence
  # para: initial parameter value
  # Output updated para value (A and B; we do not update w)
  
  for(i in 1:n.iter){
    para = BW.onestep(x, para)
  }
  return(para)
}

In [379]:
BW.onestep = function(x, para){
    # Input: 
    # x: T-by-1 observation sequence
    # para: mx, mz, and current para values for
    #    A: initial estimate for mz-by-mz transition matrix
    #    B: initial estimate for mz-by-mx emission matrix
    #    w: initial estimate for mz-by-1 initial distribution over Z_1
    # Output the updated parameters after one iteration
    # We DO NOT update the initial distribution w

    T = length(x)
    mz = para$mz
    mx = para$mx
    A = para$A
    B = para$B
    w = para$w
    alp = forward.prob(x, para)
    beta = backward.prob(x, para)
    

    myGamma = array(0, dim=c(mz, mz, T-1))
    myGamma_i = matrix(0, T, mz)
    #######################################
    ## YOUR CODE: 
    ## Compute gamma_t(i,j) P(Z[t] = i, Z[t+1]=j), 
    for (t in 1:(T-1)) {
        for (i in 1:mz) {
          for (j in 1:mz) {
            myGamma[i, j, t] = alp[t,i] * A[i,j] * B[j, x[t+1]] * beta[(t+1),j]
          }
        }
      }
    
    for (t in 1:(T-1)){
        for (i in 1:mz){
            myGamma_i[t,i] = sum(myGamma[i,,t] )
        }
    }

    for (i in 1:mz){
            myGamma_i[T,i] = sum(myGamma[,i,T-1])
        }
    

    ## which are stored in an array, myGamma
    #######################################

    # M-step for parameter A
    #######################################
    ## YOUR CODE: 
    
    A = apply(myGamma, MARGIN=c(1,2), sum)
    A = A/rowSums(A)
    
    #######################################

    # M-step for parameter B
    #######################################
    ## YOUR CODE: 

    B[] = 0
    for (i in 1:mz) {
        for (l in 1:mx) {
          idx = which(x == l)
          B[i,l] = sum(myGamma_i[idx,i]) / sum(myGamma_i[,i])
        }
      }

    #######################################

    para$A = A
    para$B = B
    return(para)
}

In [380]:
forward.prob = function(x, para){
  # Output the forward probability matrix alp 
  # alp: T by mz, (t, i) entry = P(x_{1:t}, Z_t = i)
  T = length(x)
  mz = para$mz
  A = para$A
  B = para$B
  w = para$w
  alp = matrix(0, T, mz)
  
  # fill in the first row of alp
  alp[1, ] = w * B[, x[1]]
  # Recursively compute the remaining rows of alp
  for(t in 2:T){
    tmp = alp[t-1, ] %*% A
    alp[t, ] = tmp * B[, x[t]]
    }
  return(alp)
}

backward.prob = function(x, para){
  # Output the backward probability matrix beta
  # beta: T by mz, (t, i) entry = P(x_{1:t}, Z_t = i)
  T = length(x)
  mz = para$mz
  A = para$A
  B = para$B
  w = para$w
  beta = matrix(1, T, mz)

  # The last row of beta is all 1.
  # Recursively compute the previous rows of beta
  for(t in (T-1):1){
    tmp = as.matrix(beta[t+1, ] * B[, x[t+1]])  # make tmp a column vector
    beta[t, ] = t(A %*% tmp)
    }
  return(beta)
}

In [404]:
myViterbi = function(x, para){
    # Output: most likely sequence of Z (T-by-1)
    T = length(x)
    mz = para$mz
    A = para$A
    B = para$B
    w = para$w
    log.A = log(A)
    log.w = log(w)
    log.B = log(B)

    # Compute delta (in log-scale)
    delta = matrix(0, T, mz) 
    # fill in the first row of delta
    delta[1, ] = log.w + log.B[, x[1]]

    #######################################
    ## YOUR CODE: 
    ## Recursively compute the remaining rows of delta
    for (t in 2:T){
        for (i in 1:mz){
            jVec = rep(0, mz)
            for (j in 1:mz){
                jVec[j] = delta[t-1,j] + log.A[j,i]
            }
            delta[t,i] = max(jVec) + log.B[i, x[t]]
        }
            
    }

    #######################################

    # Compute the most prob sequence Z
    Z = rep(0, T)
    # start with the last entry of Z
    Z[T] = which.max(delta[T, ])
    
    for (t in (T-1):1){
        Z[t] = which.max(delta[t,] + log.A[,Z[t+1]])
    }

    #######################################
    ## YOUR CODE: 
    ## Recursively compute the remaining entries of Z
    #######################################

    return(Z)
}

In [405]:
library(HMM)
hmm0 =initHMM(c("A", "B"), c(1, 2, 3),
              startProbs = ini.w,
              transProbs = ini.A, 
              emissionProbs = ini.B)
Rout = baumWelch(hmm0, data, maxIterations=100, delta=1E-9, pseudoCount=0)
Rout.Z = viterbi(Rout$hmm, data)

In [406]:
data = scan("coding4_part2_data.txt")

mz = 2
mx = 3
ini.w = rep(1, mz); ini.w = ini.w / sum(ini.w)
ini.A = matrix(1, 2, 2); ini.A = ini.A / rowSums(ini.A)
ini.B = matrix(1:6, 2, 3); ini.B = ini.B / rowSums(ini.B)
ini.para = list(mz = 2, mx = 3, w = ini.w,
                A = ini.A, B = ini.B)

myout = myBW(data, ini.para, n.iter = 100)

myout.Z = myViterbi(data, myout)
myout.Z[myout.Z==1] = 'A'
myout.Z[myout.Z==2] = 'B'

In [407]:
options(digits=8)
options()$digits

[1] 8

In [408]:
myout$A
Rout$hmm$transProbs

[,1]       [,2]      
[1,] 0.49793938 0.50206062
[2,] 0.44883431 0.55116569

to
from A          B         
   A 0.49793938 0.50206062
   B 0.44883431 0.55116569

In [409]:
myout$B
Rout$hmm$emissionProbs

[,1]       [,2]       [,3]      
[1,] 0.22159897 0.20266127 0.57573976
[2,] 0.34175148 0.17866665 0.47958186

symbols
states 1          2          3         
     A 0.22159897 0.20266127 0.57573976
     B 0.34175148 0.17866665 0.47958186

In [410]:
cbind(Rout.Z, myout.Z)[c(1:10, 180:200), ]
sum(Rout.Z != myout.Z)

Rout.Z myout.Z
 [1,] A      A      
 [2,] A      A      
 [3,] A      A      
 [4,] A      A      
 [5,] A      A      
 [6,] A      A      
 [7,] A      A      
 [8,] B      B      
 [9,] A      A      
[10,] A      A      
[11,] B      B      
[12,] A      A      
[13,] A      A      
[14,] A      A      
[15,] A      A      
[16,] A      A      
[17,] A      A      
[18,] A      A      
[19,] A      A      
[20,] B      B      
[21,] B      B      
[22,] B      B      
[23,] B      B      
[24,] B      B      
[25,] A      A      
[26,] A      A      
[27,] A      A      
[28,] A      A      
[29,] A      A      
[30,] A      A      
[31,] A      A

[1] 0